name: CI

on:
  push:
  pull_request:

jobs:
  ci:
    uses: roschaefer/reusable-workflows/.github/workflows/rust-ci.yml@81a1a8ada0ebe2b8fb491b2a86a58baa86b98939 # main
    permissions:
      contents: write
    with:
      binary_name: markdown-to-cucumber
