name: CI

on:
  push:
  pull_request:

jobs:
  ci:
    uses: roschaefer/reusable-workflows/.github/workflows/rust-ci.yml@ffd0237aa945c15a863404262b72f1087e8ff9c7 # main
    with:
      binary_name: markdown-to-cucumber
